### ISSUE TITLE
Generate glygen_protein_masterlist.csv for Nathan

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#723]
See #470 for steps

**Comment by kmartinez834** [comment]
@rykahsay I am getting the following connection error when I try to run /software/glygen/dump_protein_masterlist.py.  Is [SPARQL ](https://sparql.tst.glygen.org/) down?  Also, is Dictyostelium in tst.SPARQL yet or do you need to process the protein datasets first?

```
$python dump_protein_masterlist.py 
Traceback (most recent call last):
  File "dump_protein_masterlist.py", line 58, in <module>
    main()
  File "dump_protein_masterlist.py", line 28, in main
    sparqlutil.load_isoformlist(data_grid, species)
  File "/software/glygen/sparqlutil.py", line 740, in load_isoformlist
    results = sparql.query().convert()
  File "/usr/lib64/python2.7/site-packages/SPARQLWrapper/Wrapper.py", line 798, in query
    return QueryResult(self._query())
  File "/usr/lib64/python2.7/site-packages/SPARQLWrapper/Wrapper.py", line 766, in _query
    response = urlopener(request)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1244, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 111] Connection refused>
```

**Comment by rykahsay** [comment]
I was able to run it, and create the output file (/data/shared/glygen/downloads/glygen_protein_masterlist.csv). The sparql on tst/beta/prd gets updated only when we are ready to release production.

**Comment by kmartinez834** [comment]
Confirmed I could run it as well
